export const colors = {
  primary: '#B83A1C',
  primaryLight: '#FAEDE9',
  background: '#FFFFFF',
  surface: '#F5F5F3',
  border: '#E8E8E5',
  textPrimary: '#1A1A1A',
  textSecondary: '#6B6B6B',
  textTertiary: '#A0A0A0',
  openGreen: '#3B6D11',
  openGreenBg: '#EAF3DE',
  closedRed: '#A32D2D',
  closedRedBg: '#FCEBEB',
  star: '#F0A500',
  white: '#FFFFFF',
};